server:
  port: 0
spring:
  boot:
    admin:
      client:
        url: http://localhost:8888
  application:
    name: account
  datasource:
    url: jdbc:postgresql://localhost:5432/eventuate
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
eventuatelocal:
  kafka:
    bootstrap:
      servers: http://localhost:9092
  zookeeper:
    connection:
      string: http://localhost:2181