apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
{{ include "labels.standard" . | indent 4 }}
    app: {{ .Values.name }}
  annotations:
{{ toYaml .Values.servers.annotations | indent 4 }}
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: {{ .Values.application.port }}
  type:  {{ .Values.servers.serviceType }}
  selector:
    app: {{ .Values.name }}
    release: "{{ .Release.Name }}"