apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:

  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations: null
      from:
        kind: DockerImage
        name: {{ .Values.docker.repository }}/{{ .Values.docker.image }}:{{ .Chart.AppVersion }}
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
