eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
server:
  port: 0
spring:
  application:
    name: notification
  boot:
    admin:
      client:
        url: http://localhost:8888
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smptp:
          auth: true
          starttls:
            enable: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
eventuatelocal:
  kafka:
    bootstrap:
      servers: http://localhost:9092
  zookeeper:
    connection:
      string: http://localhost:2181