eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
server:
  port: 0
spring:
  application:
    name: order
  boot:
    admin:
      client:
        url: ${ADMIN_URI:http://localhost:8888}
management:
  endpoints:
    web:
      exposure:
        include: *