eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
zuul:
  prefix: /api
server:
  port: 8000
spring:
  application:
    name: gateway
  boot:
    admin:
      client:
        url: ${ADMIN_URI:http://localhost:8888}
management:
  endpoints:
    web:
      exposure:
        include: "*"