eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
server:
  port: 8883
spring:
  application:
    name: delivery
  boot:
    admin:
      client:
        url: ${ADMIN_URI:http://localhost:8888}
  datasource:
    url: jdbc:postgresql://localhost:5432/eventuate
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    generate-ddl: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
