name: order
resources:
  server:
    requests:
      memory: 300Mi
      cpu: 10m
    limits:
      memory: 4000Mi
      cpu: 1
docker:
  repository: elvaliev
  image: order
replicas: 1
uri: order-sol-portfolio-dev03.telitcaas1.t-internal.com
servers:
  serviceType: LoadBalancer  # [ClusterIP|LoadBalancer]
portName: 8083
application:
  port: 8083
  profiles: prod
pdb:
  enabled: false
  minAvailable: 1
config:
  url: http://config/
eureka:
  url: http://server/eureka