server:
  port: 8080
spring:
  boot:
    admin:
      client:
        url: http://admin:8888
  application:
    name: account
  datasource:
    url: jdbc:postgresql://postgres/eventuate
    username: eventuate
    password: eventuate
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
eventuatelocal:
  kafka:
    bootstrap:
      servers: kafka:29092
  zookeeper:
    connection:
      string: zookeeper:2181