server:
  port: 8888
spring:
  boot:
    admin:
      probed-endpoints: env, metrics, trace, jolokia, info, configprops
  application:
    name: admin
eureka:
  client:
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5