zuul:
  prefix: /api
server:
  port: 8008
spring:
  application:
    name: gateway
  boot:
    admin:
      client:
        url: ${ADMIN_URI:http://localhost:8888}
management:
  endpoints:
    web:
      exposure:
        include: "*"