eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
zuul:
  prefix: /api
server:
  port: 8008
spring:
  application:
    name: gateway
  boot:
    admin:
      client:
        url: http://admin:8888
management:
  endpoints:
    web:
      exposure:
        include: "*"