eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
server:
  port: 8085
spring:
  application:
    name: notification
  boot:
    admin:
      client:
        url: http://admin:8888
  datasource:
    url: jdbc:postgresql://postgres/eventuate
      username: eventuate
      password: eventuate
      driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    generate-ddl: true
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smptp:
          auth: true
          starttls:
            enable: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
eventuatelocal:
  kafka:
    bootstrap:
      servers: kafka:29092
  zookeeper:
    connection:
      string: zookeeper:2181